/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ParkingLot } from "./ParkingLot";
import { ParkingLotCountArgs } from "./ParkingLotCountArgs";
import { ParkingLotFindManyArgs } from "./ParkingLotFindManyArgs";
import { ParkingLotFindUniqueArgs } from "./ParkingLotFindUniqueArgs";
import { DeleteParkingLotArgs } from "./DeleteParkingLotArgs";
import { ParkingLotService } from "../parkingLot.service";
@graphql.Resolver(() => ParkingLot)
export class ParkingLotResolverBase {
  constructor(protected readonly service: ParkingLotService) {}

  async _parkingLotsMeta(
    @graphql.Args() args: ParkingLotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ParkingLot])
  async parkingLots(
    @graphql.Args() args: ParkingLotFindManyArgs
  ): Promise<ParkingLot[]> {
    return this.service.parkingLots(args);
  }

  @graphql.Query(() => ParkingLot, { nullable: true })
  async parkingLot(
    @graphql.Args() args: ParkingLotFindUniqueArgs
  ): Promise<ParkingLot | null> {
    const result = await this.service.parkingLot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ParkingLot)
  async deleteParkingLot(
    @graphql.Args() args: DeleteParkingLotArgs
  ): Promise<ParkingLot | null> {
    try {
      return await this.service.deleteParkingLot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
