/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ParkingSpot } from "./ParkingSpot";
import { ParkingSpotCountArgs } from "./ParkingSpotCountArgs";
import { ParkingSpotFindManyArgs } from "./ParkingSpotFindManyArgs";
import { ParkingSpotFindUniqueArgs } from "./ParkingSpotFindUniqueArgs";
import { DeleteParkingSpotArgs } from "./DeleteParkingSpotArgs";
import { ParkingSpotService } from "../parkingSpot.service";
@graphql.Resolver(() => ParkingSpot)
export class ParkingSpotResolverBase {
  constructor(protected readonly service: ParkingSpotService) {}

  async _parkingSpotsMeta(
    @graphql.Args() args: ParkingSpotCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ParkingSpot])
  async parkingSpots(
    @graphql.Args() args: ParkingSpotFindManyArgs
  ): Promise<ParkingSpot[]> {
    return this.service.parkingSpots(args);
  }

  @graphql.Query(() => ParkingSpot, { nullable: true })
  async parkingSpot(
    @graphql.Args() args: ParkingSpotFindUniqueArgs
  ): Promise<ParkingSpot | null> {
    const result = await this.service.parkingSpot(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ParkingSpot)
  async deleteParkingSpot(
    @graphql.Args() args: DeleteParkingSpotArgs
  ): Promise<ParkingSpot | null> {
    try {
      return await this.service.deleteParkingSpot(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
